using System;

namespace ToDo.Models;

public class ToDoTask
{
    public int Id { get; set; } // auto_generated by the database

    public string? UserId { get; set; }     // foriegn key to connect the ToDoTask table to the ApplicationUser table

    public string? Title { get; set; }

    public bool IsComplete { get; set; } = false;

    public DateTime DueDate { get; set; } = DateTime.Now;

    public ApplicationUser? User { get; set; }      // navigation prop , holds the user object itself that owns the task
        // its 1 -> M relation that each user has many tasks and each task owned by one user
}
